#!/bin/bash
# shellcheck disable=SC1003

# shellcheck disable=SC1091
source koi
koiname=lurker
koidescription="Hacker News terminal client"

# internal variables
masterpostlist=()
spinpid=
colors=1
foldsize=100
commentpids=()

function __verifyjq {
	# verify jq is installed
	# shellcheck disable=SC2091
    if ! type jq > /dev/null 2>&1 ; then
        __errortext "$koiname: err: 'jq' is not in the PATH (see: https://stedolan.github.io/jq/)"
        __errortext "  lurker uses 'jq' to process Hacker News API responses, please install it before continuing"
        return 1
    fi
}

function __getmasterlist {
	# get master list of posts (500 total)
	# $1 is the loading message to use
	__startspin "${1:-Initializing}"
	mkdir -p "${HOME}/.lurker"
	# shellcheck disable=SC2207
	masterpostlist=( $(curl -s 'https://hacker-news.firebaseio.com/v0/topstories.json' | jq -r '.[]') )
	__stopspin
}

function __drawlogo {
	echo ' ____                  __                 '
	echo '|    |    __ _________|  | __ ___________ '
	echo '|    |   |  |  \_  __ \  |/ // __ \_  __ \'
	echo '|    |___|  |  /|  | \/    <\  ___/|  | \/'
	echo '|_______ \____/ |__|  |__|_ \\___  >__|   '
	echo '        \/                 \/    \/       '
}

function __startspin {
	# start the spinner
	# $1 message to display with the spinner
	local message X
	set +m
	message="$1"
	echo -ne "$message     "
	{ while : ; do for X in '•  ' '•• ' '•••' ' ••' '  •' '   ' ; do echo -en "\b\b\b$X" ; sleep 0.1 ; done ; done & } 2>/dev/null
	spinpid=$!
}

function __stopspin {
	# stop the spinner
	{ kill -9 $spinpid && wait; } 2>/dev/null
	set -m
	echo -en "\033[2K\r"
}

function __clearintermediates {
	rm -rf "${HOME}/.lurker/"*
}

function __exitcleanly {
	__stopspin
	__clearintermediates
}

# ---------------- COLORS ---------------- #
function __gray {
	grey "$@"
}
function __grey {
	if [[ $colors -eq 1 ]] ; then
		echo -ne "\033[90m$*\033[0m"
	else
		echo -ne "$@"
	fi
}
function __red {
	if [[ $colors -eq 1 ]] ; then
		echo -ne "\033[91m$*\033[0m"
	else
		echo -ne "$@"
	fi
}
function __green {
	if [[ $colors -eq 1 ]] ; then
		echo -ne "\033[92m$*\033[0m"
	else
		echo -ne "$@"
	fi
}
function __yellow {
	if [[ $colors -eq 1 ]] ; then
		echo -ne "\033[93m$*\033[0m"
	else
		echo -ne "$@"
	fi
}
function __blue {
	if [[ $colors -eq 1 ]] ; then
		echo -ne "\033[94m$*\033[0m"
	else
		echo -ne "$@"
	fi
}
function __pink {
	if [[ $colors -eq 1 ]] ; then
		echo -ne "\033[95m$*\033[0m"
	else
		echo -ne "$@"
	fi
}
function __teal {
	if [[ $colors -eq 1 ]] ; then
		echo -ne "\033[96m$*\033[0m"
	else
		echo -ne "$@"
	fi
}
function __white {
	if [[ $colors -eq 1 ]] ; then
		echo -ne "\033[97m$*\033[0m"
	else
		echo -ne "$@"
	fi
}
# ---------------- END COLORS ---------------- #

# ---------------- GET POSTS ---------------- #
function __getposts {
	# Handle spinner and call function to get posts
	# $1 is start index
	# $2 is end index
	# $3 is loading text (optional)

	__startspin "${3:-"Fetching more posts"}"
	__getmultipleposts "$1" "$2"
}

function __getmultipleposts {
	# get posts between startindex and endindex
	# $1 is startindex
	# $2 is endindex

	local i index pids pid

	# start concurrent post requests
	pids=()
	for i in $(seq "$1" "$2") ; do
		index=$(( i + 1 ))
		__getindividualpost "$index" > "${HOME}/.lurker/${index}" &
		pids=( "${pids[@]}" $! )
	done

	# wait for all posts to be processed
	for pid in "${pids[@]}" ; do
		wait "$pid"
	done

	# display info
	__stopspin
	for i in $(seq "$1" "$2") ; do
		index=$(( i + 1 ))
		cat ~/.lurker/${index}
	done

	# reset working directory
	__clearintermediates
}

function __getindividualpost {
	# Get an individual post
	# $1 - numerical post ID
	local postid post title descendants descendantstext author score time timetext url urltext metadataindent
	postid="$1"

	# get post data
	post="$(curl -s "https://hacker-news.firebaseio.com/v0/item/${masterpostlist[(( $postid - 1 ))]}.json?print=pretty")"
	title="$(jq -r '.title' <<< "$post")"

	# determine descendants (number of comments)
	descendants="$(jq -r '.descendants' <<< "$post")"
	if [[ "$descendants" == 'null' ]] ; then
		descendantstext="comments disabled"
	elif [[ "$descendants" -eq 1 ]] ; then
		descendantstext="$descendants comment"
	else
		descendantstext="$descendants comments"
	fi

	# determine post metadata
	author="$(jq -r '.by' <<< "$post")"
	score="$(jq -r '.score' <<< "$post")"
	time="$(jq -r '.time' <<< "$post")"
	time=$(( $(date +%s) - time ))
	timetext="$(__cleantime "$time")"
	url="$(jq -r '.url' <<< "$post")"
	if [[ "$url" == 'null' ]] ; then
		urltext=
	else
		urltext="($(awk -F[/:] '{print $4}' <<< "$url"))"
	fi

	# determine indent size for metadata
	if [[ $postid -lt 10 ]] ; then
		metadataindent='   '
	elif [[ $postid -lt 100 ]] ; then
		metadataindent='    '
	else
		metadataindent='     '
	fi

	# display info
	echo -ne "${postid}. "
	echo "$(__green "$(__cleantext "$title")") $(__pink "$urltext")"
	echo "${metadataindent}$(__blue "$(__cleantext "$score")" points) $(__white by) $(__yellow "$(__cleantext "$author")") $(__white "$(__cleantext "$timetext")" "|") $(__teal "$(__cleantext "$descendantstext")")"
}
# ---------------- END GET POSTS ---------------- #

# ---------------- GET USER ---------------- #
function __getuser {
	# get user information
	# $1 is the user ID

	local id name created createdtime createdtext karma about
	id="$1"

	__startspin "Searching for user '$id'"

	if [[ "$id" == '' ]] ; then
		__stopspin
		__errortext -c "No user ID provided"
		return 1
	fi

	user="$(curl -s "https://hacker-news.firebaseio.com/v0/user/${id}.json?print=pretty")"
	if [[ "$user" == 'null' ]] ; then
		__stopspin
		__errortext -c "No such user $id"
		return 1
	fi

	name="$(jq -r '.id' <<< "$user")"
	created="$(jq -r '.created' <<< "$user")"
	createdtime=$(( $(date +%s) - created ))
	createdtext="$(__cleantime "$createdtime")"
	karma="$(jq -r '.karma' <<< "$user")"
	about="$(jq -r '.about' <<< "$user")"

	__stopspin

	echo "$(__white "User ID:") $(__pink "$(__cleantext "$name")")"
	echo "$(__white "Karma:") $(__pink "$(__cleantext "$karma")" points)"
	echo "$(__white "Created:") $(__pink "$(date -r "$created" +'%B %d, %Y') ($createdtext)")"
	if [[ "$about" != 'null' && "$about" != '' ]] ; then
		# shellcheck disable=SC2005
		echo "$(__white "About:")"
		# shellcheck disable=SC2005
		echo "$(__pink "$(__cleantext "$about")")" | fold -w "$foldsize" -s | sed "s/^/  /g"
	fi
}
# ---------------- END GET USER ---------------- #

# ---------------- GET THREAD ---------------- #
function __getthreadpost {
	# Handle spinner and call function to get posts
	# $1 is the post ID

	__startspin "Fetching post"

	local postid post children title posttext descendants descendantstext author score time timetext url urltext type parts
	postid="$1"

	# get post info
	post="$(curl -s "https://hacker-news.firebaseio.com/v0/item/${masterpostlist[(( $postid - 1 ))]}.json?print=pretty")"
	children=()
	if jq -r -e 'has("kids")' <<< "$post" > /dev/null; then
		# shellcheck disable=SC2207
		children=( $(jq -r '.kids[]' <<< "$post") )
	fi
	title="$(jq -r '.title' <<< "$post")"
	posttext=
	if jq -r -e 'has("text")' <<< "$post" > /dev/null; then
		posttext="$(jq -r '.text' <<< "$post")"
	fi
	descendants="$(jq -r '.descendants' <<< "$post")"
	if [[ "$descendants" == 'null' ]] ; then
		descendantstext="comments disabled"
	elif [[ "$descendants" -eq 1 ]] ; then
		descendantstext="$descendants comment"
	else
		descendantstext="$descendants comments"
	fi

	# get post metadata
	author="$(jq -r '.by' <<< "$post")"
	score="$(jq -r '.score' <<< "$post")"
	time="$(jq -r '.time' <<< "$post")"
	time=$(( $(date +%s) - time ))
	timetext="$(__cleantime "$time")"
	url="$(jq -r '.url' <<< "$post")"
	if [[ "$url" == 'null' ]] ; then
		urltext=
	else
		urltext="($(awk -F[/:] '{print $4}' <<< "$url"))"
	fi

	__stopspin

	# display post header info
	echo "$(__green "$(__cleantext "$title")") $(__pink "$urltext")"
	echo "$(__blue "$(__cleantext "$score")" points) $(__white by) $(__yellow "$(__cleantext "$author")") $(__white "$(__cleantext "$timetext")" "|") $(__teal "$(__cleantext "$descendantstext")")"
	if [[ "$posttext" != "" ]] ; then
		__white "$(__cleantext "$posttext" | fold -w "$foldsize" -s)\n"
	fi
	type="$(jq -r '.type' <<< "$post")"
	if [[ "$type" == 'poll' ]] ; then
		parts=( "$(jq -r '.parts[]' <<< "$post")" )
		# shellcheck disable=SC2068
		__processpoll ${parts[@]}
	fi

	# start recursive comment tree traversal for thread
	if [[ "$descendants" != 'null' ]] ; then
		if [[ $descendants -gt 0 ]] ; then
			__startspin "Fetching $descendants comments"
			__startthreadfetch "$author" "${children[@]}"
		fi
	fi
}

function __processpoll {
	# show options for poll
	# $1+ are the poll options
	local part option score scoretext text count listtext

	count=0
	for part in "$@" ; do
		option="$(curl -s "https://hacker-news.firebaseio.com/v0/item/${part}.json?print=pretty")"
		score="$(jq -r '.score' <<< "$option")"
		if [[ "$score" -eq 1 ]] ; then
			scoretext="point"
		else
			scoretext="points"
		fi
		if [[ "$count" -eq $(( $# - 1 )) ]] ; then
			listtext=' └──'
		else
			listtext=' ├──'
		fi
		text="$(jq -r '.text' <<< "$option")"
		echo "$(__white "$listtext") $(__pink "${score} ${scoretext}") $(__white "| $(__cleantext "$text")")"
		(( count += 1 ))
	done
}

function __startthreadfetch {
	# Intermediate function to handle recursion cleanly
	# $1 is the post author (OP)
	# $2+ are the list of children to traverse for __getthreadcomments

	# start concurrent comment requests
	local pid f files op
	op="$1"
	shift

	# start concurrent comment requests
	commentpids=()
	__getthreadcomments 0 "" "$op" "$@" &
	commentpids=( $! )

	# wait for all comments to be processed
	for pid in "${commentpids[@]}" ; do
		wait "$pid"
	done

	# display info
	__stopspin
	# shellcheck disable=SC2207
	files=( $(__sortcomments "") )
	for f in "${files[@]}" ; do
		cat "$f"
	done

	# reset working directory
	__clearintermediates
}

function __sortcomments {
	# sort a set of processed comments (as filenames)
	# $1 is the filename prefix
	local count prefix
	prefix="$1"
	shift

	count=0
	while : ; do
		if [[ -f ~/.lurker/${prefix}${count} ]] ; then
			echo "${HOME}/.lurker/${prefix}${count}"
			if [[ -f ~/.lurker/${prefix}${count}.0 ]] ; then
				__sortcomments "${prefix}${count}."
			fi
		else
			break
		fi
		(( count += 1 ))
	done
}

function __getthreadcomments {
	# get comments for thread
	# $1 is the depth of our recursion
	# $2 is the filename prefix
	# $3 is the post author (OP)
	# $3+ is the list of children to traverse

	local depth prefix op count child comment indent author authortext commenttext time timetext deleted dead children commentfile
	depth="$1"
	prefix="$2"
	op="$3"
	shift 3

	count=0
	for child in "$@" ; do
		# get comment info
		comment="$(curl -s "https://hacker-news.firebaseio.com/v0/item/$child.json?print=pretty")"
		
		# calculate indent
		indent=
		for _ in $(seq 0 "$depth") ; do
			indent="${indent}    "
		done

		# get comment information
		author="$(jq -r '.by' <<< "$comment")"
		commenttext="$(jq -r '.text' <<< "$comment")"
		time="$(jq -r '.time' <<< "$comment")"
		time=$(( $(date +%s) - time ))
		timetext="$(__cleantime $time)"
		deleted="$(jq -r '.deleted' <<< "$comment")"
		dead="$(jq -r '.dead' <<< "$comment")"

		# skip if comment has been deleted
		if [[ "$deleted" == 'true' || "$dead" == 'true' ]] ; then
			continue
		fi

		if [[ "$prefix" == "" ]] ; then
			commentfile="${count}"
		else
			commentfile="${prefix}.${count}"
		fi

		if [[ "$author" == "$op" ]] ; then
			authortext="$(__yellow "$author") $(__white "|") $(__teal "[OP]")"
		else
			authortext="$author"
		fi

		# display comment information
		echo "${indent}$(__teal "$(__cleantext "$authortext")") $(__white "|") $(__teal "$timetext:")" > "${HOME}/.lurker/${commentfile}"
		__white "$(__cleantext "$commenttext" | fold -w "$foldsize" -s | sed "s/^/${indent}/")\n" >> "${HOME}/.lurker/${commentfile}"

		# calculate children to continue traversal
		children=()
		if jq -r -e 'has("kids")' <<< "$comment" > /dev/null; then
			# shellcheck disable=SC2207
			children=( $(jq -r '.kids[]' <<< "$comment") )
		fi
		if [[ ${#children[@]} -gt 0 ]] ; then
			__getthreadcomments $(( depth + 1 )) "$commentfile" "$op" "${children[@]}" &
			commentpids=( "${commentpids[@]}" $! )
		fi
		(( count += 1 ))
	done
}
# ---------------- END GET THREAD ---------------- #

# ---------------- MAIN LOOP ---------------- #
function __lurk {
	# start REPL
	
	local startindex endindex prompt key id disp post url untouchedkey smooshoutput
	startindex=0
	endindex=$(( startindex + 9 ))

	__getposts "$startindex" "$endindex" "Fetching posts"
	prompt="\033[2K\033[E> "

	while : ; do
		echo -ne "$prompt"
		if [[ "$command" == "" ]] ; then
			IFS='' read -r key
		else
			key="$command"
			echo "$command"
			command=
		fi

		# if key is a number
		[ -n "$key" ] && [ "$key" -eq "$key" ] 2>/dev/null
		# shellcheck disable=SC2181
		if [[ $? -eq 0 ]] ; then
			if [[ $key -lt 501  && $key -gt 0 ]] ; then
				__getindividualpost "$key"
			else
				__errortext -c "Post index must be between 1 and 500"
			fi
			continue
		fi

		# if key is a command
		untouchedkey="$key"
		key="$(tr '[:upper:]' '[:lower:]' <<< "$key")"
		case "$key" in
			read*)
				id="${key#read*}"
				[ -n "$id" ] && [ "$id" -eq "$id" ] 2>/dev/null
				# shellcheck disable=SC2181
				if [[ $? -ne 0 ]] ; then
					__errortext -c "Post index must be a number"
					continue
				fi
				if [[ $id -lt 1 || $id -gt 500 ]] ; then
					__errortext -c "Post index must be between 1 and 500"
					continue
				fi
				__getthreadpost "$id"
				;;
			b|back|again)
				__getposts "$startindex" "$endindex" "Fetching posts again  "
				;;
			m|more)
				startindex=$(( endindex + 1 ))
				endindex=$(( startindex + 9 ))
				__getposts "$startindex" "$endindex"
				;;
			l|less)
				if [[ "$startindex" -gt 9 ]] ; then
					endindex=$(( startindex - 1 ))
					startindex=$(( endindex - 9 ))
					__getposts "$startindex" "$endindex" "Fetching previous posts  "
				else
					__errortext -c "Post index must be between 1 and 500"
				fi
				;;
			open*)
				id="${key#open*}"
				[ -n "$id" ] && [ "$id" -eq "$id" ] 2>/dev/null
				# shellcheck disable=SC2181
				if [[ $? -ne 0 ]] ; then
					__errortext -c "Post index must be a number"
					continue
				fi
				if [[ $id -lt 0 || $id -gt 500 ]] ; then
					__errortext -c "Post index must be between 1 and 500"
					continue
				fi
				post="$(curl -s "https://hacker-news.firebaseio.com/v0/item/${masterpostlist[(( $id - 1 ))]}.json?print=pretty")"
				url="$(jq -r '.url' <<< "$post")"
				if [[ "$url" == 'null' ]] ; then
					__errortext -c "No URL specified for this post"
					continue
				fi
				if [[ "$(uname -s)" == *Darwin* ]] ; then
					open "${url//\"/}"
				else
					__errortext -c "Sorry, this feature is only available on macOS. Here's the link you'd like to open:"
					echo "${url//\"/}"
				fi
				;;
			smoosh*)
				if [[ "$(uname -s)" != *Darwin* ]] ; then
					__errortext -c "Sorry, this feature is only available on macOS. Learn more about smoosh: https://github.com/wcarhart/smoosh"
					continue
				fi
				# verify smoosh is installed
				# https://github.com/wcarhart/smoosh
				if ! type smoosh > /dev/null 2>&1 ; then
					__errortext -c "Smoosh is not currently installed. Smoosh is a CLI for summarizing text. Lurker uses smooosh to summarize HN articles."
					__errortext -c "Lurker does not ship with smoosh pre-installed because it is an optional feature. Please install smoosh before continuing."
					__errortext -c ""
					__errortext -c "You can install smoosh with:"
					__errortext -c "  brew install wcarhart/tools/smoosh"
					__errortext -c ""
					__errortext -c "Read more: https://github.com/wcarhart/smoosh"
					continue
				fi
				id="${key#smoosh*}"
				[ -n "$id" ] && [ "$id" -eq "$id" ] 2>/dev/null
				# shellcheck disable=SC2181
				if [[ $? -ne 0 ]] ; then
					__errortext -c "Post index must be a number"
					continue
				fi
				if [[ $id -lt 0 || $id -gt 500 ]] ; then
					__errortext -c "Post index must be between 1 and 500"
					continue
				fi
				post="$(curl -s "https://hacker-news.firebaseio.com/v0/item/${masterpostlist[(( $id - 1 ))]}.json?print=pretty")"
				url="$(jq -r '.url' <<< "$post")"
				if [[ "$url" == 'null' ]] ; then
					__errortext -c "No URL specified for this post"
					continue
				fi
				if smooshoutput="$(smoosh --omit-metrics --sentence-limit 7 "${url//\"/}")" ; then
					# shellcheck disable=SC2005
					echo "$(__green "$smooshoutput")" | fold -w "$foldsize" -s
				else
					__errortext -c "$smooshoutput"
				fi
				;;
			hack*)
				id="${key#hack*}"
				[ -n "$id" ] && [ "$id" -eq "$id" ] 2>/dev/null
				# shellcheck disable=SC2181
				if [[ $? -ne 0 ]] ; then
					__errortext -c "Post index must be a number"
					continue
				fi
				if [[ $id -lt 0 || $id -gt 500 ]] ; then
					__errortext -c "Post index must be between 1 and 500"
					continue
				fi
				url="https://news.ycombinator.com/item?id=${masterpostlist[(( $id - 1 ))]}"
				if [[ "$(uname -s)" == *Darwin* ]] ; then
					open "${url//\"/}"
				else
					__errortext -c "Sorry, this feature is only available on macOS. Here's the link you'd like to open:"
					echo "${url//\"/}"
				fi
				;;
			copy*)
				id="${key#copy*}"
				[ -n "$id" ] && [ "$id" -eq "$id" ] 2>/dev/null
				# shellcheck disable=SC2181
				if [[ $? -ne 0 ]] ; then
					__errortext -c "Post index must be a number"
					continue
				fi
				if [[ $id -lt 0 || $id -gt 500 ]] ; then
					__errortext -c "Post index must be between 1 and 500"
					continue
				fi
				post="$(curl -s "https://hacker-news.firebaseio.com/v0/item/${masterpostlist[(( $id - 1 ))]}.json?print=pretty")"
				url="$(jq -r '.url' <<< "$post")"
				if [[ "$url" == 'null' ]] ; then
					__errortext -c "No URL specified for this post"
					continue
				fi
				if [[ "$(uname -s)" == *Darwin* ]] ; then
					echo -n "${url//\"/}" | pbcopy
				else
					__errortext -c "Sorry, this feature is only available on macOS. Here's the link you'd like to copy:"
					echo "${url//\"/}"
				fi
				;;
			user*)
				id="${untouchedkey:5}"
				__getuser "$id"
				;;
			clear)
				clear
				;;
			refresh)
				__getmasterlist "Refreshing"
				startindex=0
				endindex=$(( startindex + 9 ))
				__getposts "$startindex" "$endindex" "Fetching posts"
				;;
			h|help|list)
				echo "Available commands:"
				echo "  help        - show this help menu"
				echo "  read <ID>   - open the comment thread for post ID"
				echo "  open <ID>   - open the URL for the post ID in your default browser (only available on macOS)"
				echo "  copy <ID>   - copy the URL for the post ID to the clipboard (only available on macOS)"
				echo "  hack <ID>   - open the Hacker News link for the post ID in your default browser (only available on macOS)"
				echo "  smoosh <ID> - summarize (smoosh) the content from the URL for post ID (only available on macOS)"
				echo "  user <ID>   - show info for user ID"
				echo "  <ID>        - get info for post ID"
				echo "  more        - show the next 10 posts (up to 500)"
				echo "  less        - show the previous 10 posts"
				echo "  back        - show the previous list of posts again"
				echo "  refresh     - refresh the master post list, which will reset the ordering of posts"
				echo "  clear       - clear the screen"
				echo "  exit        - quit lurker"
				;;
			q|e|quit|exit|'done'|'/exit'|'/quit'|'/done'|'/q'|'exit()'|'quit()'|'done()'|'.exit'|'.quit'|'.done')
				echo
				exit 0
				;;
			'')
				continue
				;;
			*)
				# shellcheck disable=SC2206
				key=( $key )
				disp="'${key[0]}'"
				__errortext -c "Unknown command $disp"
				__errortext -c "Type 'help' for command list"
				;;
		esac
	done
}
# ---------------- END MAIN LOOP ---------------- #

# ---------------- CLEAN DATA ---------------- #
function __cleantime {
	# clean time into a human readable format
	# $1 is the time elapsed in seconds

	local time timetext
	time="$1"

	if [[ "$time" -lt 60 ]] ; then
		if [[ "$time" -eq 1 ]] ; then
			timetext="$time second ago"
		else
			timetext="$time seconds ago"
		fi
	elif [[ "$time" -ge 60 && "$time" -lt 3600 ]] ; then
		time=$(( time / 60 ))
		if [[ "$time" -eq 1 ]] ; then
			timetext="$time minute ago"
		else
			timetext="$time minutes ago"
		fi
	elif [[ "$time" -ge 3600 && "$time" -lt 86400 ]]; then
		time=$(( time / 3600 ))
		if [[ "$time" -eq 1 ]] ; then
			timetext="$time hour ago"
		else
			timetext="$time hours ago"
		fi
	elif [[ "$time" -ge 86400 && "$time" -lt 604800 ]] ; then
		time=$(( time / 86400 ))
		if [[ $time -eq 1 ]] ; then
			timetext="Yesterday"
		else
			timetext="$time days ago"
		fi
	elif [[ "$time" -ge 604800 && "$time" -lt 2629746 ]] ; then
		time=$(( time / 604800 ))
		if [[ $time -eq 1 ]] ; then
			timetext="$time week ago"
		else
			timetext="$time weeks ago"
		fi
	elif [[ "$time" -ge 2629746 && "$time" -lt 31556952 ]] ; then
		time=$(( time / 2629746 ))
		if [[ $time -eq 1 ]] ; then
			timetext="$time month ago"
		else
			timetext="$time months ago"
		fi
	elif [[ "$time" -ge 31556952 && "$time" -lt 3155695200 ]] ; then
		time=$(( time / 31556952 ))
		if [[ $time -eq 1 ]] ; then
			timetext="$time year ago"
		else
			timetext="$time years ago"
		fi
	else
		time=$(( time / 3155695200 ))
		if [[ $time -eq 1 ]] ; then
			timetext="$time century ago"
		else
			timetext="$time centuries ago"
		fi
	fi
	echo "$timetext"
}

function __cleantext {
	# clean text into terminal friendly format
	# $@ is the text to clean

	local content

	content="$(echo "$@" | sed \
	-e 's/&gt;/>/g' \
	-e 's/&#62;/>/g' \
	-e 's/&lt;/</g' \
	-e 's/&#60;/</g' \
	-e "s/&#x27;/'/g" \
	-e 's/&quot;/"/g' \
	-e 's/\&amp;/\&/g' \
	-e 's/<i>/_/g' \
	-e 's;</i>;_;g' \
	-e 's/<b>/**/g' \
	-e 's;</b>;**;g' \
	-e 's/<strong>/**/g' \
	-e 's;</strong>;**;g' \
	-e 's~&#x2F;~/~g' \
	-e 's~<a .*\(href=\\"[^\\"]*\).*</a>~\1~g' \
	-e 's~href=\\"~~g' \
	-e 's~<a .*\(href="[^"]*\).*</a>~\1~g' \
	-e 's~href="~~g')"
	if [[ "$(uname -s)" == *Darwin* ]] ; then
		# shellcheck disable=SC2016
		content="$(echo "$content" | sed \
		-e 's/<p>/\\\n\\\n/g' \
		-e 's/<br>/\\\n\\\n/g' \
		-e 's/<pre><code>/```\\\n/g' \
		-e 's;</code></pre>;\\\n```\\\n;g' \
		-e 's/<code>/```\\\n/g' \
		-e 's;</code>;\\\n```\\\n;g')"
	else
		# shellcheck disable=SC2016
		content="$(echo "$content" | sed \
		-e 's/<p>/\n\n/g' \
		-e 's/<br>/\n\n/g' \
		-e 's/<pre><code>/```\n/g' \
		-e 's;</code></pre>;\n```\n;g' \
		-e 's/<code>/```\n/g' \
		-e 's;</code>;\n```\n;g')"
	fi
	echo -e "$content"
}
# ---------------- END CLEAN DATA ---------------- #

function __verifynumber {
	# verify that an argument is a number

	local returncode
	returncode=0

	set +e
	[ -n "$1" ] && [ "$1" -eq "$1" ] 2>/dev/null
	# shellcheck disable=SC2181
	if [[ $? -ne 0 ]] ; then
	    __errortext "$koiname: err: argument for '--foldsize' must be an integer"
	    returncode=1
	elif [[ "$1" -lt 80 ]] ; then
		__errortext "$koiname: err: minimum fold size is 80"
		returncode=1
	fi
	set -e
	return "$returncode"
}

function __koimain {
	__addarg "-h" "--help" "help" "optional" "" "$koidescription"
	__addarg "-n" "--nocolors" "flag" "optional" "" "Do not use colors in output"
	__addarg "-f" "--foldsize" "storevalue" "optional" "100" "The line length at which to wrap" "__verifynumber"
	__addarg "-c" "--command" "storevalue" "optional" "" "Run a lurker command when lurker starts"
	__addarg "-s" "--silent" "flag" "optional" "" "Do not print the lurker logo when lurker starts"
	__parseargs "$@"

	# once arguments are parsed, disable exit on errors
	set +e

	# set up colors
	# shellcheck disable=SC2154
	if [[ $nocolors -eq 1 ]] ; then
		colors=0
	elif [[ "$(tput colors)" -eq 0 ]] ; then
		__errortext "$koiname: err: colors are not supported on this terminal"
		return 1
	fi

	# verify jq is installed
	__verifyjq

	# determine if should draw logo or not
	# shellcheck disable=SC2154
	if [[ $silent -eq 0 ]] ; then
		__drawlogo
	fi

	# initialize post list
	__getmasterlist

	# register cleanup trap
	trap __exitcleanly EXIT

	# begin lurking :)
	__lurk
}

__koirun "$@"
